### ISSUE TITLE
Exec key is not parsed

### ISSUE THREAD

**Issue by willemw12** [kspi/dmenu-frecency#4]
Some of the Exec key values from .desktop files are passed (incorrectly) to the launched program.

For example,

    gwenview.desktop:Exec=gwenview %U -caption %c %i

Results in error message:

    Loading ‘%i’ failed
    Could not open file /home/willem/%i

And the window title is "%c".

Desktop Exec key specification: http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

BTW, I have created a package for Arch Linux (https://aur.archlinux.org/packages/dmenu-frecency-git/).

**Comment by kspi** [comment]
I implemented parsing of the Exec key without regexes in a899210f7c8e39b2bd59c9c045a170af4cdbb5e7 using shlex. Hopefully it works well. The state format changed slightly so visits are cleared when updating.

**Comment by willemw12** [comment]
Some issues I found. When launching 'KDE Dolphin':

    Exec=dolphin %i -caption %c %u

the window title is `system-file-manager - Dolphin`, expected `<my user name> - Dolphin`.

Launching 'KDE System Settings'

    Exec=systemsettings -caption %c %i

fails:

    $ dmenu-frecency                    
    systemsettings: Unexpected argument 'preferences-system'.
    systemsettings: Use --help to get a list of available command line options.

**Comment by kspi** [comment]
Ah, I misread the specification for %i, it should be fixed now.

**Comment by willemw12** [comment]
Still getting the same issues with commit 952e8fa.

**Comment by kspi** [comment]
Does the issue persist after launching 'dmenu-frecency --read-apps'? The relevant code is only executed when updating the cache. Dolphin and Gwenview launch properly for me.

**Comment by willemw12** [comment]
That solved it (removed the cache before running 'dmenu-frecency --read-apps').
